### PR TITLE
fix(typings): handle one more type of es6 exports

### PR DESCRIPTION
**Pull request by Heymdall**
Fix for https://github.com/KnisterPeter/react-to-typescript-definitions/issues/286

### CODE REVIEW

**Comment by KnisterPeter** [comment]
Awesome, could you please provide a unit test for that. I'll happy to merge then. :smile:

**Comment by Heymdall** [comment]
done!

**Comment by KnisterPeter** [comment]
I think the line endings of the test result file are wrong. Everything else looks fine.

I should correct them during test execution. I will merge your changes as soon as possible.

**Comment by KnisterPeter** [comment]
Released as 0.18.1

Thank you!

**Pull request merged**
