### PR TITLE
feat: allow users to set additional babylon plugins

### PR DESCRIPTION
**Pull request by muzea**
fix: https://github.com/KnisterPeter/react-to-typescript-definitions/issues/608

### CODE REVIEW

**Comment by KnisterPeter** [comment]
Awesome. I'll review and merge in a view days as soon as I have time. :rocket:

**Comment by KnisterPeter** [comment]
A test case would be cool.

**Comment by muzea** [comment]
Ok, I will add the test later.

**Comment by KnisterPeter** [comment]
@muzea Any update on the missing tests?

**Comment by muzea** [comment]
@KingHenne done.

**Comment by KnisterPeter** [comment]
@muzea Cool. Thanks for your contribution. I'll make a release in a few moments.

**Pull request merged**
